on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    - name: Deploy
      uses: appleboy/ssh-action@master
      with:
        HOST: ${{ secrets.HOST }}
        USERNAME: ${{ secrets.USERNAME }}
        PORT: ${{ secrets.PORT }}
        KEY: ${{ secrets.SSHKEY }}
        script: |
          cd public_html/travaux/wr506-symfony
          git pull origin main
          composer install
          php bin/console c:c
          php bin/console d:s:u --complete --force

          php bin/console doctrine:fixtures:load --no-interaction || (echo "Fixture loading failed" && exit 1)

          echo "Deployment successful"
